### ISSUE TITLE
能否加上权限控制

### ISSUE THREAD

**Issue by barryqiu** [JoneXiong/PyRedisAdmin#12]
web管理界面能否加上登录权限控制？这样可以提高一点安全性，防止数据被恶意操作。

**Comment by JoneXiong** [comment]
恩，后面考虑加入简单的角色控制和权限验证

**Comment by koaqiu** [comment]
我认为“本地访问控制”即可

对外开放的服务（端口）越多，安全性问题就越大

如果限制只能本地访问，那就可以省下大量精力（处理安全性问题需要消耗大量资源）用来提升这管理器本身的功能（Redis数据管理）

**Comment by JoneXiong** [comment]
:+1:

**Comment by yuezheng** [comment]
是不是考虑添加web端的redis登陆，以替代配置文件的方式？

**Comment by JoneXiong** [comment]
马上下一个版本就加上的

**Comment by JoneXiong** [comment]
"登录权限控制"已加入master
