### ISSUE TITLE
打开出错

### ISSUE THREAD

**Issue by jerrylisuzhou** [JoneXiong/PyRedisAdmin#5]
![default](https://cloud.githubusercontent.com/assets/6766669/6775140/ae84dbea-d167-11e4-9654-fcece1a738d2.png)

**Comment by JoneXiong** [comment]
redis 是哪个版本？

**Comment by jerrylisuzhou** [comment]
![image](https://cloud.githubusercontent.com/assets/6766669/6819835/a5af3d8e-d302-11e4-859b-1b74d1916559.png)

**Comment by JoneXiong** [comment]
是较新的redis版本，估计要更新下redis-py库，你先用v2.10.0版本试试 地址：https://github.com/andymccurdy/redis-py/tree/2.10.0  我稍后会更新PyRedisAdmin的版本兼容性

**Comment by hengchengfei** [comment]
我也遇到这个问题了,请问解决了嘛

**Comment by JoneXiong** [comment]
已更新修复
