### ISSUE TITLE
希望能支持查看反序列化的数据

### ISSUE THREAD

**Issue by yangghost** [JoneXiong/PyRedisAdmin#9]
我的redis数据是序列化进去的.查看数据就会报错.
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 1189: invalid start byte
这个好像比较麻烦..很多序列化算法.

**Comment by JoneXiong** [comment]
好的,尽快加上！

**Comment by JoneXiong** [comment]
查看序列化的数据标错的问题已经修复,。因为每个语言每个第三方库序列化的方法不一样，所里这里仅原样显示序列化后的字符串内容
